# Generated by Django 5.0.4 on 2024-04-19 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель ведущего моста')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель двигателя')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель техники')),
                ('description', models.TextField(verbose_name='Описание ')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название справочника')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('description', models.TextField(default='Клиент', max_length=255, verbose_name='Описание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('reference_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.referenceentity', verbose_name='Название справочника')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Заводской № машины')),
                ('engine_serial_number', models.CharField(max_length=255, unique=True, verbose_name='Заводской № двигателя')),
                ('transmission_serial_number', models.CharField(max_length=255, unique=True, verbose_name='Заводской № трансмиссии')),
                ('drive_axle_serial_number', models.CharField(max_length=255, verbose_name='Заводской № ведущего моста')),
                ('steer_axle_serial_number', models.CharField(max_length=255, verbose_name='Заводской № управляемого моста')),
                ('delivery_contract', models.CharField(max_length=255, verbose_name='Договор поставки (№, дата)')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('end_user', models.CharField(max_length=255, verbose_name='Грузополучатель (конечный потребитель)')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='Адрес поставки (эксплуатации)')),
                ('configuration', models.TextField(default='Стандарт', max_length=1000, verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.client', verbose_name='Клиент')),
                ('drive_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.driveaxlemodel', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.enginemodel', verbose_name='Модель двигателя')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.machinemodel', verbose_name='Модель техники')),
                ('reference_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.referenceentity', verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид ТО')),
                ('description', models.TextField(verbose_name='Описание')),
                ('reference_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.referenceentity', verbose_name='Название справочника')),
            ],
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='reference_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.referenceentity', verbose_name='Название справочника'),
        ),
        migrations.CreateModel(
            name='FailureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Узел отказа')),
                ('description', models.TextField(verbose_name='Описание')),
                ('reference_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.referenceentity', verbose_name='Название справочника')),
            ],
        ),
        migrations.AddField(
            model_name='enginemodel',
            name='reference_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.referenceentity', verbose_name='Название справочника'),
        ),
        migrations.AddField(
            model_name='driveaxlemodel',
            name='reference_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.referenceentity', verbose_name='Название справочника'),
        ),
        migrations.CreateModel(
            name='RepairProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Способ восстановления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('reference_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.referenceentity', verbose_name='Название справочника')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Сервисная компания', max_length=255, verbose_name='Описание')),
                ('reference_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.referenceentity', verbose_name='Название справочника')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.IntegerField(default=0, verbose_name='Наработка, м/час')),
                ('failure_description', models.TextField(max_length=1000, verbose_name='Описание отказа')),
                ('spare_parts', models.TextField(blank=True, max_length=1000, verbose_name='Используемые запасные части')),
                ('repair_date', models.DateField(verbose_name='Дата восстановления')),
                ('nonuse_time', models.IntegerField(default=0, verbose_name='Время простоя техники')),
                ('failure_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.failureunit', verbose_name='Узел отказа')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.machine', verbose_name='Машина')),
                ('reference_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.referenceentity', verbose_name='Название справочника')),
                ('repair_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.repairprocedure', verbose_name='Способ восстановления')),
                ('service_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.servicedepartment', verbose_name='Сервисная компания')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='service_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.servicedepartment', verbose_name='Сервисная компания'),
        ),
        migrations.CreateModel(
            name='ServiceTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Организация, проводившая ТО', max_length=255, verbose_name='Описание')),
                ('reference_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.referenceentity', verbose_name='Название справочника')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.IntegerField(default=0, verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=255, verbose_name='Номер заказ-наряда')),
                ('order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.machine', verbose_name='Машина')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.maintenancetype', verbose_name='Вид ТО')),
                ('reference_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.referenceentity', verbose_name='Название справочника')),
                ('service_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.servicedepartment', verbose_name='Сервисная компания')),
                ('maintenance_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.serviceto', verbose_name='Организация, проводившая ТО')),
            ],
        ),
        migrations.CreateModel(
            name='SteerAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель управляемого моста')),
                ('description', models.TextField(verbose_name='Описание')),
                ('reference_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.referenceentity', verbose_name='Название справочника')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='steer_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.steeraxlemodel', verbose_name='Модель управляемого моста'),
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель трансмиссии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('reference_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.referenceentity', verbose_name='Название справочника')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
    ]
