# Generated by Django 5.0.4 on 2024-05-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='configuration',
            field=models.TextField(default='Стандарт', max_length=100, verbose_name='Комплектация (доп. опции)'),
        ),
    ]
