# Generated by Django 5.0.4 on 2024-05-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant_app', '0002_alter_machine_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='configuration',
            field=models.TextField(default='Стандарт', max_length=80, verbose_name='Комплектация (доп. опции)'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='failure_description',
            field=models.TextField(max_length=80, verbose_name='Описание отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='spare_parts',
            field=models.TextField(blank=True, max_length=80, verbose_name='Используемые запасные части'),
        ),
    ]
